#@data/values
---
workloadNamespace: acme
devDefaultAccountUsername: acme
devDefaultAccountPassword: <redacted>
ingressDomain: tap.example.com
applicationName: acme-fitness
httpProxy:
  virtualhost:
    #    fqdn: <applicationName>.<ingressDomain>
    fqdn: acme-fitness.tap.example.com
#appSSORedirectURI: http://<httpProxy.virtualHost.fqdn>/login/oauth2/code/sso
#clientRegistrationName: <applicationName>-client-registration
clientRegistrationName: acme-fitness-client-registration
#appSSOIssuerURI: http://appsso-<applicationName><workloadNamespace>.<ingressDomain>
appSSOIssuerURI: http://appsso-acme-fitness.acme.tap.example.com
redisPassword: <redacted>
